
spring:
  application:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8050
          predicates:
            - Path=/api/authservice/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowedHeaders: "*"
            allowCredentials: true
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info

jwt:
  secret: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4

service:
  url: http://localhost

services:
  auth:
    url: http://localhost:8050
  fleet:
    url: http://localhost:8090
  device:
    url: http://localhost:8090